### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by lattln**
+ groundwork
+ react
+ express
+ tailwind css +file structure
+ basic routing
+ mock prototype page
+ removed NextJS

### CODE REVIEW

**Comment by lattln** [comment]
image

**Comment by lattln** [comment]
@zeshengchen, we removed Next from our stack and will be sticking to the base React.

**Review by zeshengchen — APPROVED** [review]
The basic framework looks good to me.

**Review by Nguyen-Noah — APPROVED** [review]

**Review by myeken — APPROVED** [review]

**Comment by lattln** [comment]
merging pull request -- all approvals accepted

**Pull request merged**
